- src/main/java/org/mifos/connector/common/channel/dto/TransactionChannelC2BRequestDTO.java
Updating logic for C2B transactions generated by channel request.
@avikganguly01 : Please review and merge
> Updating values for channel request dto

- src/main/java/org/mifos/connector/common/gsma/dto/CustomData.java
- src/main/java/org/mifos/connector/common/gsma/dto/GsmaTransfer.java
- src/main/java/org/mifos/connector/common/gsma/dto/Party.java
- added gsma transfer dto
- custom data class
- payer payee class
@avikganguly01 @fynmanoj
> Gsma transfer DTO

- src/main/java/org/mifos/connector/common/channel/dto/PhErrorDTO.java
- src/main/java/org/mifos/connector/common/exception/PaymentHubError.java
- src/main/java/org/mifos/connector/common/exception/PaymentHubErrorCategory.java
* Added new error category, `VALIDATION`.
* Added new error codes.
> New error category and pherrors added

- src/main/java/org/mifos/connector/common/mojaloop/dto/Party.java
- added lombok for constructors, getters and setters and to string method
@avikganguly01 @fynmanoj
> Added lombok to party class

- src/main/java/org/mifos/connector/common/ams/dto/LoanRepaymentDTO.java
> Added loan repayment DTO

- src/main/java/org/mifos/connector/common/channel/dto/TransactionChannelRequestDTO.java
- added custom data to collection api
> Added custom data to collection api

- build.gradle
- src/main/java/org/mifos/connector/common/util/MpesaUtils.java
- src/main/java/org/mifos/connector/common/util/ZeebeUtil.java
- src/main/java/org/mifos/connector/common/zeebe/ZeebeClientConfiguration.java
- src/main/java/org/mifos/connector/common/zeebe/ZeebeProcessStarter.java
- src/main/java/org/mifos/connector/common/zeebe/ZeebeVariables.java
- src/main/resources/application.yml
*Added Zeebe Process Starter Code to connector common.
> Zeebe Starter Code

- src/main/java/org/mifos/connector/common/gsma/dto/CustomData.java
> Changed custom data value type

- src/main/java/org/mifos/connector/common/ams/dto/LoanRepaymentDTO.java
- src/main/java/org/mifos/connector/common/gsma/dto/CustomData.java
- src/main/java/org/mifos/connector/common/mojaloop/dto/Party.java
add the 1.2.3 release changes to master
> V1.2.3 release

- src/main/java/org/mifos/connector/common/identityaccountmapper/dto/AccountLookupResponseDTO.java
- src/main/java/org/mifos/connector/common/identityaccountmapper/dto/AccountMapperRequestDTO.java
- src/main/java/org/mifos/connector/common/identityaccountmapper/dto/BeneficiaryDTO.java
- src/main/java/org/mifos/connector/common/identityaccountmapper/dto/CallbackDTO.java
- src/main/java/org/mifos/connector/common/identityaccountmapper/dto/FailedCaseDTO.java
- src/main/java/org/mifos/connector/common/identityaccountmapper/dto/PaymentModalityDTO.java
* Adding the DTO for Identity Account Mapper Service.
> Identity Account Mapper DTO

- README.md
- src/main/java/org/mifos/connector/common/interceptor/WebMvcConfig.java
- src/main/java/org/mifos/connector/common/interceptor/config/WebSignatureConfiguration.java
* Fixed the boot issue of channel connector with `1.4.0` version of connector-common.
> Patch-RELEASE-1.4.0: Fixed the bug in WebMvcConfig boot

- src/main/java/org/mifos/connector/common/channel/dto/TransactionChannelRequestDTO.java
- Changing custom data type to array
Jira Ticket : https://mifosforge.jira.com/browse/GOV-267
> [GOV- 267] Changing custom data type to array

- src/main/java/org/mifos/connector/common/vouchers/dto/CallbackRequestDTO.java
- src/main/java/org/mifos/connector/common/vouchers/dto/FailedCaseDTO.java
- src/main/java/org/mifos/connector/common/vouchers/dto/RedeemVoucherRequestDTO.java
- src/main/java/org/mifos/connector/common/vouchers/dto/RedeemVoucherResponseDTO.java
- src/main/java/org/mifos/connector/common/vouchers/dto/RequestDTO.java
- src/main/java/org/mifos/connector/common/vouchers/dto/ResponseDTO.java
- src/main/java/org/mifos/connector/common/vouchers/dto/SuccessfulVouchers.java
- src/main/java/org/mifos/connector/common/vouchers/dto/ValidityDTO.java
- src/main/java/org/mifos/connector/common/vouchers/dto/VoucherInstruction.java
- src/main/java/org/mifos/connector/common/vouchers/dto/VoucherLifecycleCallbackResponseDTO.java
> Voucher DTO

- src/main/java/org/mifos/connector/common/batch/dto/AuthorizationRequest.java
- src/main/java/org/mifos/connector/common/batch/dto/AuthorizationResponse.java
Jira link: [GOV-301](https://mifosforge.jira.com/browse/GOV-301)
[GOV-301]: https://mifosforge.jira.com/browse/GOV-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-301: Add batch authorization request and response

- src/main/java/org/mifos/connector/common/interceptor/JWSUtil.java
- src/main/java/org/mifos/connector/common/interceptor/WebMvcConfig.java
- src/main/java/org/mifos/connector/common/interceptor/WebSignatureInterceptor.java
* Bug fixes
https://github.com/openMF/ph-ee-bulk-processor/pull/100
https://github.com/openMF/ph-ee-env-template/pull/211
https://mifosforge.jira.com/browse/GOV-289
https://fynarfin.atlassian.net/browse/PHEE-402?atlOrigin=eyJpIjoiM2MyYWJmNzkzNWQwNDMwOWIyYTljNGUwZGJlYWJiOGUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
> GOV-289 Bug fixes in parsing empty payload

- src/main/java/org/mifos/connector/common/operations/dto/Transfer.java
This PR adds error information field to Transfer class. Error information is needed to check if the transaction is duplicate or not.
[GOV-325](https://mifosforge.jira.com/browse/GOV-325)
[GOV-325]: https://mifosforge.jira.com/browse/GOV-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-325: Update transfer class with error information and other fields

- build.gradle
- src/main/java/org/mifos/connector/common/interceptor/JWSUtil.java
- src/main/java/org/mifos/connector/common/interceptor/MultiReadFilter.java
- src/main/java/org/mifos/connector/common/interceptor/WebMvcConfig.java
- src/main/java/org/mifos/connector/common/interceptor/WebSignatureInterceptor.java
- src/main/java/org/mifos/connector/common/interceptor/helper/ByteArrayServletInputStream.java
- src/main/java/org/mifos/connector/common/interceptor/helper/MultiReadHttpServletRequest.java
* Implemented the multi-read HttpServletRequest wrapper.
* Injected the MultiReadHttpRequest using the filter.
* Updated the JWSUtil to use MultiReadHttpRequest for parsing the json based payload and form data.
[PHEE-413](https://fynarfin.atlassian.net/browse/PHEE-413)
[PHEE-413]: https://fynarfin.atlassian.net/browse/PHEE-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PHEE-413 Fixed the bug while verifying signature in the interceptor

- build.gradle
- src/main/java/org/mifos/connector/common/interceptor/JWSUtil.java
* Fixed the big
[PHEE-420](https://fynarfin.atlassian.net/browse/PHEE-420)
[PHEE-420]: https://fynarfin.atlassian.net/browse/PHEE-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixes PHEE-420: Extra newline while verifying signature

- README.md
- build.gradle
- src/main/java/org/mifos/connector/common/util/JsonWebSignature.java
* Created a `JwsSignature` and `JwsSignatureBuilder` for simplifying the process of creating the JWS.
[PHEE-479](https://fynarfin.atlassian.net/browse/PHEE-479)
[PHEE-479]: https://fynarfin.atlassian.net/browse/PHEE-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PHEE-479: Added jws builder for creating json web signature

- src/main/java/org/mifos/connector/common/channel/dto/Errors.java
- src/main/java/org/mifos/connector/common/channel/dto/PhErrorDTO.java
[PHEE-492 Modify ErrorDTO for Error Aggregation](https://fynarfin.atlassian.net/browse/PHEE-492?atlOrigin=eyJpIjoiMjkzZTIwMGM0M2E1NDY5MGJjMGQxMDJhOWFiYTRmNWQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-492] Modify ErrorDTO for Error Aggregation

- .circleci/config.yml
- build.gradle
- settings.gradle
(https://fynarfin.atlassian.net/browse/PHEE-421)
* Added config file to Deploy artifact to Jfrog through CircleCI pipeline
* Added [rootProject.name = 'ph-ee-connector-common'] in the settings.gradle to point to exact artifact in the Jfrog 
> PHEE-421 Deploy to artifact through CircleCI

- build.gradle
- src/main/java/org/mifos/connector/common/interceptor/JWSUtil.java
[PHEE-535 Extract content type boundary logic fix.](https://fynarfin.atlassian.net/browse/PHEE-535?atlOrigin=eyJpIjoiNjVlNjQ0YTlmNDdlNGVjOTk0MWI0ZThmN2NhZjI0YTYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-535] Extract content type boundary logic fix.

- build.gradle
- src/main/java/org/mifos/connector/common/webclient/WebClientAdapter.java
* Describe the changes made and why they were made.
> [PHEE-564] Webclient and Callback Adapter Added

- .circleci/config.yml
- build.gradle
[](https://fynarfin.atlassian.net/browse/PHEE-421)
* Describe the changes made and why they were made.
> [PHEE-421] Deploy Artifact to Jfrog for tag version

- src/main/java/org/mifos/connector/common/validation/ValidatorBuilder.java
* Describe the changes made and why they were made.
> [phee-665] Add common functions to validator builder
